version: "3.9"

networks:

  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:

  db_vol:
    name: db
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_PATH}ft_data/db

  upload:
    name: upload
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_PATH}ft_data/upload

  backend:
    name: backend
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_PATH}ft_transcendence/backend

  contracts:
    name: contracts
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_PATH}ft_transcendence/contracts

  frontend:
    name: frontend
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_PATH}ft_transcendence/frontend

  pong:
    name: pong
    driver_opts:
      type: none
      o: bind
      device: ${PROJECT_PATH}ft_transcendence/pong

services:

  db:
    image: postgres:14
    container_name: db
    env_file: .env
    restart: always
    ports:
      - "${DB_OUT_PORT}:${DB_PORT}"
    volumes:
      - db_vol:/var/lib/postgresql/data/${DB_NAME}
    networks:
      - ft_transcendence

  backend:
    build:
      context: ./backend
    image: backend:img
    container_name: backend
    env_file: .env
    restart: always
    depends_on:
      - db
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    volumes:
      - frontend:/frontend
      - backend:/backend
      - contracts:/contracts
      - pong:/pong
      - upload:/upload
    networks:
      - ft_transcendence

  frontend:
    build:
      context: ./frontend
    image: frontend:img
    container_name: frontend
    env_file: .env
    restart: always
    depends_on:
      - pong
    ports:
      - "${HOST_PORT}:${FRONT_PORT}"
    volumes:
      - frontend:/frontend
      - backend:/backend
      - contracts:/contracts
      - pong:/pong
    networks:
      - ft_transcendence

  pong:
    build:
      context: ./pong
    image: pong:img
    container_name: pong
    env_file: .env
    restart: always
    depends_on:
      - backend
    ports:
      - "${PONG_PORT}:${PONG_PORT}"
    volumes:
      - pong:/pong
    networks:
      - ft_transcendence